### ISSUE TITLE
access denied at https://camera-trap.tw/project/overview

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#155]
目前在 prod 上以新的 orcid 登入會自動導向到 https://camera-trap.tw/project/overview
然後看到如下的頁面：

![Screenshot 2019-05-24 23 42 09](https://user-images.githubusercontent.com/31983251/58340173-cbfedc80-7e7d-11e9-8c20-358281e58fcb.png)

**Comment by f2ejack** [comment]
Here are the headers info which getting via different environment login then redirect to overview page, for your reference:

### dev

General
  Request URL: **https://dev.camera-trap.tw/project/overview**
  Request Method: GET
  Status Code: 200 
  Remote Address: 13.35.37.32:443
  Referrer Policy: no-referrer-when-downgrade
Response Headers
  age: 507
  content-encoding: gzip
  **content-type: text/html**
  date: Wed, 22 May 2019 13:32:45 GMT
  last-modified: Wed, 22 May 2019 09:04:13 GMT
  server: AmazonS3
  status: 200
  vary: Accept-Encoding
  via: 1.1 e668d88e6448a10ef6988cd750ecddad.cloudfront.net (CloudFront)
  x-amz-cf-id: t9Y9xsq46NCXWQYFIzd4M-y6qtyjUngUrBp7LLcsboiwSUSe_lXWWQ==
  x-cache: Error from cloudfront
Request Headers
  :authority: **dev.camera-trap.tw**
  :method: GET
  :path: /project/overview
  :scheme: https
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
  accept-encoding: gzip, deflate, br
  accept-language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,ja;q=0.5,fr;q=0.4,de;q=0.3,ru;q=0.2,ko;q=0.1,ar;q=0.1
  if-modified-since: Wed, 22 May 2019 09:04:13 GMT
  upgrade-insecure-requests: 1
  user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

### prod.

General
  Request URL: **https://camera-trap.tw/project/overview**
  Request Method: GET
  Status Code: 403 
  Remote Address: 13.35.165.48:443
  Referrer Policy: no-referrer-when-downgrade
Response Headers
  **content-type: application/xml**
  date: Fri, 24 May 2019 20:58:46 GMT
  server: AmazonS3
  status: 403
  via: 1.1 7c6f489e1b803fe5e697678a76a7ae7e.cloudfront.net (CloudFront)
  x-amz-cf-id: LmTz-RF5_QkZSa6rbTb7yZIeSbOAdcVnuOlnYT2UFsJ41wzC-Ku4bg==
  x-cache: Error from cloudfront
Request Headers
  :authority: **camera-trap.tw**
  :method: GET
  :path: /project/overview
  :scheme: https
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
  accept-encoding: gzip, deflate, br
  accept-language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-CN;q=0.6,ja;q=0.5,fr;q=0.4,de;q=0.3,ru;q=0.2,ko;q=0.1,ar;q=0.1
  referer: https://orcid.org/signin?oauth&client_id=APP-IH5RRJQDCHYQ2U5O&redirect_uri=https%3A%2F%2Fapi.camera-trap.tw%2Fcallback%2Forcid%2Fauth&response_type=code&scope=%2Fauthenticate
  upgrade-insecure-requests: 1
  user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by kelp404** [comment]
修了
<img width="1121" alt="螢幕快照 2019-05-25 上午10 30 14" src="https://user-images.githubusercontent.com/1680868/58363529-22990480-7ed8-11e9-8be6-6940e87db604.png">

**Comment by cjk-halodule** [comment]
Fix confirmed.
